
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	
	private global::Gtk.Action FileAction;
	
	private global::Gtk.Action openAction;
	
	private global::Gtk.Action quitAction;
	
	private global::Gtk.Action HelpAction;
	
	private global::Gtk.Action helpAction;
	
	private global::Gtk.Action AboutMyNesGTKAction;
	
	private global::Gtk.Action SettingsAction;
	
	private global::Gtk.Action VideoAction;
	
	private global::Gtk.Action AudioAction;
	
	private global::Gtk.Action PathsAction;
	
	private global::Gtk.Action PreferencesAction;
	
	private global::Gtk.Action openAction1;
	
	private global::Gtk.Action VideoSettingsAction;
	
	private global::Gtk.Action AudioSettingsAction;
	
	private global::Gtk.Action PathsSettingsAction;
	
	private global::Gtk.Action PreferencesAction1;
	
	private global::Gtk.Action helpAction1;
	
	private global::Gtk.Action AboutAction;
	
	private global::Gtk.Action PaletteAction;
	
	private global::Gtk.Action PaletteAction1;
	
	private global::Gtk.Action InputAction;
	
	private global::Gtk.Action InputAction1;
	
	private global::Gtk.Action copyAction;
	
	private global::Gtk.Action saveAction;
	
	private global::Gtk.Action refreshAction;
	
	private global::Gtk.Action goBackAction;
	
	private global::Gtk.Action goForwardAction;
	
	private global::Gtk.Action openAction2;
	
	private global::Gtk.Action PlayAction;
	
	private global::Gtk.Action StopAction;
	
	private global::Gtk.Action EmulationAction;
	
	private global::Gtk.Action PlaySelectedAction;
	
	private global::Gtk.Action StopSelectedAction;
	
	private global::Gtk.Action deleteAction;
	
	private global::Gtk.Action RecentAction;
	
	private global::Gtk.VBox vbox1;
	
	private global::Gtk.MenuBar menubar1;
	
	private global::Gtk.Toolbar toolbar1;
	
	private global::Gtk.HBox hbox1;
	
	private global::Gtk.HPaned hpaned1hpaned1;
	
	private global::Gtk.FileChooserWidget filechooserwidget2;
	
	private global::Gtk.VPaned vpaned1;
	
	private global::Gtk.Notebook notebook2;
	
	private global::Gtk.VBox vbox2;
	
	private global::Gtk.Toolbar toolbar2;
	
	private global::Gtk.ScrolledWindow GtkScrolledWindow2;
	
	private global::Gtk.TreeView treeview2;
	
	private global::Gtk.Label label2;
	
	private global::Gtk.Table table1;
	
	private global::Gtk.Button button1;
	
	private global::Gtk.Button button2;
	
	private global::Gtk.Button button3;
	
	private global::Gtk.Button button4;
	
	private global::Gtk.CheckButton checkbutton_enable_gg;
	
	private global::Gtk.ComboBox combobox_gg_codes;
	
	private global::Gtk.Label label4;
	
	private global::Gtk.Label label5;
	
	private global::Gtk.Label label3;
	
	private global::Gtk.Table table2;
	
	private global::Gtk.CheckButton checkbutton_loadstate;
	
	private global::Gtk.ComboBox combobox_state;
	
	private global::Gtk.Image image_state;
	
	private global::Gtk.Label label6;
	
	private global::Gtk.Label label1;
	
	private global::Gtk.Notebook notebook1;
	
	private global::Gtk.VBox vbox3;
	
	private global::Gtk.Toolbar toolbar3;
	
	private global::Gtk.Image image_snap;
	
	private global::Gtk.Statusbar statusbar1;
	
	private global::Gtk.Label label7;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.FileAction = new global::Gtk.Action ("FileAction", global::Mono.Unix.Catalog.GetString ("_File"), null, null);
		this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_File");
		w1.Add (this.FileAction, null);
		this.openAction = new global::Gtk.Action ("openAction", global::Mono.Unix.Catalog.GetString ("_Open"), global::Mono.Unix.Catalog.GetString ("Open nes rom"), "gtk-open");
		this.openAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Open");
		w1.Add (this.openAction, null);
		this.quitAction = new global::Gtk.Action ("quitAction", global::Mono.Unix.Catalog.GetString ("_Quit"), null, "gtk-quit");
		this.quitAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Quit");
		w1.Add (this.quitAction, null);
		this.HelpAction = new global::Gtk.Action ("HelpAction", global::Mono.Unix.Catalog.GetString ("_Help"), null, null);
		this.HelpAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Help");
		w1.Add (this.HelpAction, null);
		this.helpAction = new global::Gtk.Action ("helpAction", global::Mono.Unix.Catalog.GetString ("_Help"), null, "gtk-help");
		this.helpAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Help");
		w1.Add (this.helpAction, "F1");
		this.AboutMyNesGTKAction = new global::Gtk.Action ("AboutMyNesGTKAction", global::Mono.Unix.Catalog.GetString ("_About My Nes GTK"), null, "MyNesIcon");
		this.AboutMyNesGTKAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_About My Nes GTK");
		w1.Add (this.AboutMyNesGTKAction, null);
		this.SettingsAction = new global::Gtk.Action ("SettingsAction", global::Mono.Unix.Catalog.GetString ("_Settings"), null, null);
		this.SettingsAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Settings");
		w1.Add (this.SettingsAction, null);
		this.VideoAction = new global::Gtk.Action ("VideoAction", global::Mono.Unix.Catalog.GetString ("_Video"), global::Mono.Unix.Catalog.GetString ("Configure emulation video settings"), "VideoSettings");
		this.VideoAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Video");
		w1.Add (this.VideoAction, "<Primary><Alt>v");
		this.AudioAction = new global::Gtk.Action ("AudioAction", global::Mono.Unix.Catalog.GetString ("Audio"), global::Mono.Unix.Catalog.GetString ("Configure emulation audio settings"), "Audio");
		this.AudioAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Audio");
		w1.Add (this.AudioAction, "<Primary><Alt>a");
		this.PathsAction = new global::Gtk.Action ("PathsAction", global::Mono.Unix.Catalog.GetString ("_Paths"), global::Mono.Unix.Catalog.GetString ("Configure emulation paths settings"), "Paths");
		this.PathsAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Paths");
		w1.Add (this.PathsAction, "<Primary><Alt>p");
		this.PreferencesAction = new global::Gtk.Action ("PreferencesAction", global::Mono.Unix.Catalog.GetString ("_Preferences"), global::Mono.Unix.Catalog.GetString ("Configure emulation preferences ..."), "Preferences");
		this.PreferencesAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Preferences");
		w1.Add (this.PreferencesAction, "<Primary><Alt>q");
		this.openAction1 = new global::Gtk.Action ("openAction1", global::Mono.Unix.Catalog.GetString ("Open rom"), global::Mono.Unix.Catalog.GetString ("Open rom"), "gtk-open");
		this.openAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("Open rom");
		w1.Add (this.openAction1, null);
		this.VideoSettingsAction = new global::Gtk.Action ("VideoSettingsAction", global::Mono.Unix.Catalog.GetString ("Video Settings"), global::Mono.Unix.Catalog.GetString ("Configure emulation video"), "VideoSettings");
		this.VideoSettingsAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Video Settings");
		w1.Add (this.VideoSettingsAction, null);
		this.AudioSettingsAction = new global::Gtk.Action ("AudioSettingsAction", global::Mono.Unix.Catalog.GetString ("Audio Settings"), global::Mono.Unix.Catalog.GetString ("Configure emulation audio"), "Audio");
		this.AudioSettingsAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Audio Settings");
		w1.Add (this.AudioSettingsAction, null);
		this.PathsSettingsAction = new global::Gtk.Action ("PathsSettingsAction", global::Mono.Unix.Catalog.GetString ("Paths Settings"), global::Mono.Unix.Catalog.GetString ("Configure emulation paths settings"), "Paths");
		this.PathsSettingsAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Paths Settings");
		w1.Add (this.PathsSettingsAction, null);
		this.PreferencesAction1 = new global::Gtk.Action ("PreferencesAction1", global::Mono.Unix.Catalog.GetString ("Preferences"), global::Mono.Unix.Catalog.GetString ("Emulation preferences"), "Preferences");
		this.PreferencesAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("Preferences");
		w1.Add (this.PreferencesAction1, null);
		this.helpAction1 = new global::Gtk.Action ("helpAction1", global::Mono.Unix.Catalog.GetString ("Help"), null, "gtk-help");
		this.helpAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("Help");
		w1.Add (this.helpAction1, null);
		this.AboutAction = new global::Gtk.Action ("AboutAction", global::Mono.Unix.Catalog.GetString ("About"), global::Mono.Unix.Catalog.GetString ("About My Nes GTK"), "MyNesIcon");
		this.AboutAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("About");
		w1.Add (this.AboutAction, null);
		this.PaletteAction = new global::Gtk.Action ("PaletteAction", global::Mono.Unix.Catalog.GetString ("_Palette"), global::Mono.Unix.Catalog.GetString ("Configure emu color palettes"), "Palette");
		this.PaletteAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Palette");
		w1.Add (this.PaletteAction, "<Primary><Alt>w");
		this.PaletteAction1 = new global::Gtk.Action ("PaletteAction1", global::Mono.Unix.Catalog.GetString ("Palette"), global::Mono.Unix.Catalog.GetString ("Configure emu color palettes"), "Palette");
		this.PaletteAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("Palette");
		w1.Add (this.PaletteAction1, null);
		this.InputAction = new global::Gtk.Action ("InputAction", global::Mono.Unix.Catalog.GetString ("_Input"), null, "Input");
		this.InputAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Input");
		w1.Add (this.InputAction, "<Primary><Alt>e");
		this.InputAction1 = new global::Gtk.Action ("InputAction1", global::Mono.Unix.Catalog.GetString ("Input"), global::Mono.Unix.Catalog.GetString ("Configure input"), "Input");
		this.InputAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("Input");
		w1.Add (this.InputAction1, null);
		this.copyAction = new global::Gtk.Action ("copyAction", global::Mono.Unix.Catalog.GetString ("Copy"), global::Mono.Unix.Catalog.GetString ("Copy info to clipboard"), "gtk-copy");
		this.copyAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Copy");
		w1.Add (this.copyAction, null);
		this.saveAction = new global::Gtk.Action ("saveAction", global::Mono.Unix.Catalog.GetString ("Save"), global::Mono.Unix.Catalog.GetString ("Save info to text file"), "gtk-save");
		this.saveAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Save");
		w1.Add (this.saveAction, null);
		this.refreshAction = new global::Gtk.Action ("refreshAction", global::Mono.Unix.Catalog.GetString ("Refresh"), global::Mono.Unix.Catalog.GetString ("Refresh selected file info"), "gtk-refresh");
		this.refreshAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Refresh");
		w1.Add (this.refreshAction, null);
		this.goBackAction = new global::Gtk.Action ("goBackAction", global::Mono.Unix.Catalog.GetString ("Previous"), global::Mono.Unix.Catalog.GetString ("Show the previous image"), "gtk-go-back");
		this.goBackAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Previous");
		w1.Add (this.goBackAction, null);
		this.goForwardAction = new global::Gtk.Action ("goForwardAction", global::Mono.Unix.Catalog.GetString ("Next"), global::Mono.Unix.Catalog.GetString ("Show the next snap"), "gtk-go-forward");
		this.goForwardAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Next");
		w1.Add (this.goForwardAction, null);
		this.openAction2 = new global::Gtk.Action ("openAction2", global::Mono.Unix.Catalog.GetString ("Open location"), global::Mono.Unix.Catalog.GetString ("Open image folder"), "gtk-open");
		this.openAction2.ShortLabel = global::Mono.Unix.Catalog.GetString ("Open location");
		w1.Add (this.openAction2, null);
		this.PlayAction = new global::Gtk.Action ("PlayAction", global::Mono.Unix.Catalog.GetString ("Play"), global::Mono.Unix.Catalog.GetString ("Play selected game"), "Play");
		this.PlayAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Play");
		w1.Add (this.PlayAction, null);
		this.StopAction = new global::Gtk.Action ("StopAction", global::Mono.Unix.Catalog.GetString ("Stop"), global::Mono.Unix.Catalog.GetString ("Stop current game"), "Stop");
		this.StopAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Stop");
		w1.Add (this.StopAction, null);
		this.EmulationAction = new global::Gtk.Action ("EmulationAction", global::Mono.Unix.Catalog.GetString ("_Emulation"), null, null);
		this.EmulationAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Emulation");
		w1.Add (this.EmulationAction, null);
		this.PlaySelectedAction = new global::Gtk.Action ("PlaySelectedAction", global::Mono.Unix.Catalog.GetString ("_Play selected"), null, "Play");
		this.PlaySelectedAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Play selected");
		w1.Add (this.PlaySelectedAction, "<Primary>space");
		this.StopSelectedAction = new global::Gtk.Action ("StopSelectedAction", global::Mono.Unix.Catalog.GetString ("_Stop selected"), null, "Stop");
		this.StopSelectedAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Stop selected");
		w1.Add (this.StopSelectedAction, "<Primary>x");
		this.deleteAction = new global::Gtk.Action ("deleteAction", global::Mono.Unix.Catalog.GetString ("Delete"), global::Mono.Unix.Catalog.GetString ("Delete this snapshot file"), "gtk-delete");
		this.deleteAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Delete");
		w1.Add (this.deleteAction, null);
		this.RecentAction = new global::Gtk.Action ("RecentAction", global::Mono.Unix.Catalog.GetString ("Recent"), null, null);
		this.RecentAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Recent");
		w1.Add (this.RecentAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("My Nes GTK");
		this.Icon = global::Gdk.Pixbuf.LoadFromResource ("MyNesGTK.resources.MyNes.ico");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString (@"<ui><menubar name='menubar1'><menu name='FileAction' action='FileAction'><menuitem name='openAction' action='openAction'/><separator/><menuitem name='quitAction' action='quitAction'/></menu><menu name='EmulationAction' action='EmulationAction'><menuitem name='PlaySelectedAction' action='PlaySelectedAction'/><menuitem name='StopSelectedAction' action='StopSelectedAction'/></menu><menu name='SettingsAction' action='SettingsAction'><menuitem name='VideoAction' action='VideoAction'/><menuitem name='PaletteAction' action='PaletteAction'/><menuitem name='AudioAction' action='AudioAction'/><menuitem name='InputAction' action='InputAction'/><menuitem name='PathsAction' action='PathsAction'/><menuitem name='PreferencesAction' action='PreferencesAction'/></menu><menu name='HelpAction' action='HelpAction'><menuitem name='helpAction' action='helpAction'/><separator/><menuitem name='AboutMyNesGTKAction' action='AboutMyNesGTKAction'/></menu></menubar></ui>");
		this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar1")));
		this.menubar1.Name = "menubar1";
		this.vbox1.Add (this.menubar1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.menubar1]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString (@"<ui><toolbar name='toolbar1'><toolitem name='openAction1' action='openAction1'/><separator/><toolitem name='VideoSettingsAction' action='VideoSettingsAction'/><toolitem name='PaletteAction1' action='PaletteAction1'/><toolitem name='AudioSettingsAction' action='AudioSettingsAction'/><toolitem name='InputAction1' action='InputAction1'/><toolitem name='PathsSettingsAction' action='PathsSettingsAction'/><toolitem name='PreferencesAction1' action='PreferencesAction1'/><separator/><toolitem name='PlayAction' action='PlayAction'/><toolitem name='StopAction' action='StopAction'/><separator/><toolitem name='AboutAction' action='AboutAction'/><toolitem name='helpAction1' action='helpAction1'/></toolbar></ui>");
		this.toolbar1 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget ("/toolbar1")));
		this.toolbar1.Name = "toolbar1";
		this.toolbar1.ShowArrow = false;
		this.toolbar1.ToolbarStyle = ((global::Gtk.ToolbarStyle)(2));
		this.toolbar1.IconSize = ((global::Gtk.IconSize)(2));
		this.vbox1.Add (this.toolbar1);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.toolbar1]));
		w3.Position = 1;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.hpaned1hpaned1 = new global::Gtk.HPaned ();
		this.hpaned1hpaned1.CanFocus = true;
		this.hpaned1hpaned1.Name = "hpaned1hpaned1";
		this.hpaned1hpaned1.Position = 431;
		// Container child hpaned1hpaned1.Gtk.Paned+PanedChild
		this.filechooserwidget2 = new global::Gtk.FileChooserWidget (((global::Gtk.FileChooserAction)(0)));
		this.filechooserwidget2.Name = "filechooserwidget2";
		this.hpaned1hpaned1.Add (this.filechooserwidget2);
		global::Gtk.Paned.PanedChild w4 = ((global::Gtk.Paned.PanedChild)(this.hpaned1hpaned1 [this.filechooserwidget2]));
		w4.Resize = false;
		// Container child hpaned1hpaned1.Gtk.Paned+PanedChild
		this.vpaned1 = new global::Gtk.VPaned ();
		this.vpaned1.CanFocus = true;
		this.vpaned1.Name = "vpaned1";
		this.vpaned1.Position = 207;
		// Container child vpaned1.Gtk.Paned+PanedChild
		this.notebook2 = new global::Gtk.Notebook ();
		this.notebook2.CanFocus = true;
		this.notebook2.Name = "notebook2";
		this.notebook2.CurrentPage = 0;
		// Container child notebook2.Gtk.Notebook+NotebookChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><toolbar name=\'toolbar2\'><toolitem name=\'refreshAction\' action=\'refreshAction" +
		"\'/><toolitem name=\'saveAction\' action=\'saveAction\'/></toolbar></ui>");
		this.toolbar2 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget ("/toolbar2")));
		this.toolbar2.Name = "toolbar2";
		this.toolbar2.ShowArrow = false;
		this.toolbar2.ToolbarStyle = ((global::Gtk.ToolbarStyle)(0));
		this.toolbar2.IconSize = ((global::Gtk.IconSize)(2));
		this.vbox2.Add (this.toolbar2);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.toolbar2]));
		w5.Position = 0;
		w5.Expand = false;
		w5.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
		this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
		this.treeview2 = new global::Gtk.TreeView ();
		this.treeview2.CanFocus = true;
		this.treeview2.Name = "treeview2";
		this.GtkScrolledWindow2.Add (this.treeview2);
		this.vbox2.Add (this.GtkScrolledWindow2);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.GtkScrolledWindow2]));
		w7.Position = 1;
		this.notebook2.Add (this.vbox2);
		// Notebook tab
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Game Info");
		this.notebook2.SetTabLabel (this.vbox2, this.label2);
		this.label2.ShowAll ();
		// Container child notebook2.Gtk.Notebook+NotebookChild
		this.table1 = new global::Gtk.Table (((uint)(5)), ((uint)(3)), false);
		this.table1.Name = "table1";
		this.table1.RowSpacing = ((uint)(6));
		this.table1.ColumnSpacing = ((uint)(6));
		// Container child table1.Gtk.Table+TableChild
		this.button1 = new global::Gtk.Button ();
		this.button1.CanFocus = true;
		this.button1.Name = "button1";
		this.button1.UseUnderline = true;
		this.button1.Label = global::Mono.Unix.Catalog.GetString ("Add");
		this.table1.Add (this.button1);
		global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table1 [this.button1]));
		w9.TopAttach = ((uint)(2));
		w9.BottomAttach = ((uint)(3));
		w9.LeftAttach = ((uint)(1));
		w9.RightAttach = ((uint)(2));
		w9.XOptions = ((global::Gtk.AttachOptions)(4));
		w9.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.button2 = new global::Gtk.Button ();
		this.button2.CanFocus = true;
		this.button2.Name = "button2";
		this.button2.UseUnderline = true;
		this.button2.Label = global::Mono.Unix.Catalog.GetString ("Remove");
		this.table1.Add (this.button2);
		global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table1 [this.button2]));
		w10.TopAttach = ((uint)(2));
		w10.BottomAttach = ((uint)(3));
		w10.LeftAttach = ((uint)(2));
		w10.RightAttach = ((uint)(3));
		w10.XOptions = ((global::Gtk.AttachOptions)(4));
		w10.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.button3 = new global::Gtk.Button ();
		this.button3.CanFocus = true;
		this.button3.Name = "button3";
		this.button3.UseUnderline = true;
		this.button3.Label = global::Mono.Unix.Catalog.GetString ("Reload");
		this.table1.Add (this.button3);
		global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table1 [this.button3]));
		w11.TopAttach = ((uint)(1));
		w11.BottomAttach = ((uint)(2));
		w11.LeftAttach = ((uint)(1));
		w11.RightAttach = ((uint)(2));
		w11.XOptions = ((global::Gtk.AttachOptions)(4));
		w11.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.button4 = new global::Gtk.Button ();
		this.button4.CanFocus = true;
		this.button4.Name = "button4";
		this.button4.UseUnderline = true;
		this.button4.Label = global::Mono.Unix.Catalog.GetString ("Save");
		this.table1.Add (this.button4);
		global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table1 [this.button4]));
		w12.TopAttach = ((uint)(1));
		w12.BottomAttach = ((uint)(2));
		w12.LeftAttach = ((uint)(2));
		w12.RightAttach = ((uint)(3));
		w12.XOptions = ((global::Gtk.AttachOptions)(4));
		w12.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.checkbutton_enable_gg = new global::Gtk.CheckButton ();
		this.checkbutton_enable_gg.CanFocus = true;
		this.checkbutton_enable_gg.Name = "checkbutton_enable_gg";
		this.checkbutton_enable_gg.Label = global::Mono.Unix.Catalog.GetString ("Enable game genie for this game");
		this.checkbutton_enable_gg.DrawIndicator = true;
		this.checkbutton_enable_gg.UseUnderline = true;
		this.table1.Add (this.checkbutton_enable_gg);
		global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table1 [this.checkbutton_enable_gg]));
		w13.XOptions = ((global::Gtk.AttachOptions)(4));
		w13.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.combobox_gg_codes = global::Gtk.ComboBox.NewText ();
		this.combobox_gg_codes.Name = "combobox_gg_codes";
		this.table1.Add (this.combobox_gg_codes);
		global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table1 [this.combobox_gg_codes]));
		w14.TopAttach = ((uint)(2));
		w14.BottomAttach = ((uint)(3));
		w14.XOptions = ((global::Gtk.AttachOptions)(4));
		w14.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label4 = new global::Gtk.Label ();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Codes:");
		this.table1.Add (this.label4);
		global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table1 [this.label4]));
		w15.TopAttach = ((uint)(1));
		w15.BottomAttach = ((uint)(2));
		w15.XOptions = ((global::Gtk.AttachOptions)(4));
		w15.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label5 = new global::Gtk.Label ();
		this.label5.Name = "label5";
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Notes: \n. Check the \"Enable game genie for this game\" to start selected game with" +
		" game genie.\n. Press Reload to load the game genie codes for this game from the " +
		"saved file.\n. After editing the Game Genie codes you must save via Save button t" +
		"o apply them.");
		this.label5.Wrap = true;
		this.table1.Add (this.label5);
		global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table1 [this.label5]));
		w16.TopAttach = ((uint)(3));
		w16.BottomAttach = ((uint)(4));
		w16.XOptions = ((global::Gtk.AttachOptions)(4));
		this.notebook2.Add (this.table1);
		global::Gtk.Notebook.NotebookChild w17 = ((global::Gtk.Notebook.NotebookChild)(this.notebook2 [this.table1]));
		w17.Position = 1;
		// Notebook tab
		this.label3 = new global::Gtk.Label ();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Game Genie");
		this.notebook2.SetTabLabel (this.table1, this.label3);
		this.label3.ShowAll ();
		// Container child notebook2.Gtk.Notebook+NotebookChild
		this.table2 = new global::Gtk.Table (((uint)(3)), ((uint)(3)), false);
		this.table2.Name = "table2";
		this.table2.RowSpacing = ((uint)(6));
		this.table2.ColumnSpacing = ((uint)(6));
		// Container child table2.Gtk.Table+TableChild
		this.checkbutton_loadstate = new global::Gtk.CheckButton ();
		this.checkbutton_loadstate.CanFocus = true;
		this.checkbutton_loadstate.Name = "checkbutton_loadstate";
		this.checkbutton_loadstate.Label = global::Mono.Unix.Catalog.GetString ("Load state at game start");
		this.checkbutton_loadstate.DrawIndicator = true;
		this.checkbutton_loadstate.UseUnderline = true;
		this.table2.Add (this.checkbutton_loadstate);
		global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.table2 [this.checkbutton_loadstate]));
		w18.RightAttach = ((uint)(2));
		w18.XOptions = ((global::Gtk.AttachOptions)(4));
		w18.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.combobox_state = global::Gtk.ComboBox.NewText ();
		this.combobox_state.AppendText (global::Mono.Unix.Catalog.GetString ("Slot 0"));
		this.combobox_state.AppendText (global::Mono.Unix.Catalog.GetString ("Slot 1"));
		this.combobox_state.AppendText (global::Mono.Unix.Catalog.GetString ("Slot 2"));
		this.combobox_state.AppendText (global::Mono.Unix.Catalog.GetString ("Slot 3"));
		this.combobox_state.AppendText (global::Mono.Unix.Catalog.GetString ("Slot 4"));
		this.combobox_state.AppendText (global::Mono.Unix.Catalog.GetString ("Slot 5"));
		this.combobox_state.AppendText (global::Mono.Unix.Catalog.GetString ("Slot 6"));
		this.combobox_state.AppendText (global::Mono.Unix.Catalog.GetString ("Slot 7"));
		this.combobox_state.AppendText (global::Mono.Unix.Catalog.GetString ("Slot 8"));
		this.combobox_state.AppendText (global::Mono.Unix.Catalog.GetString ("Slot 9"));
		this.combobox_state.Name = "combobox_state";
		this.combobox_state.Active = 0;
		this.table2.Add (this.combobox_state);
		global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.table2 [this.combobox_state]));
		w19.TopAttach = ((uint)(1));
		w19.BottomAttach = ((uint)(2));
		w19.LeftAttach = ((uint)(1));
		w19.RightAttach = ((uint)(2));
		w19.XOptions = ((global::Gtk.AttachOptions)(4));
		w19.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.image_state = new global::Gtk.Image ();
		this.image_state.Name = "image_state";
		this.image_state.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("MyNesGTK.resources.MyNesImage.png");
		this.table2.Add (this.image_state);
		global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.table2 [this.image_state]));
		w20.TopAttach = ((uint)(2));
		w20.BottomAttach = ((uint)(3));
		w20.LeftAttach = ((uint)(1));
		w20.RightAttach = ((uint)(2));
		w20.XOptions = ((global::Gtk.AttachOptions)(4));
		w20.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.label6 = new global::Gtk.Label ();
		this.label6.Name = "label6";
		this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("State slot:");
		this.table2.Add (this.label6);
		global::Gtk.Table.TableChild w21 = ((global::Gtk.Table.TableChild)(this.table2 [this.label6]));
		w21.TopAttach = ((uint)(1));
		w21.BottomAttach = ((uint)(2));
		w21.XOptions = ((global::Gtk.AttachOptions)(4));
		w21.YOptions = ((global::Gtk.AttachOptions)(4));
		this.notebook2.Add (this.table2);
		global::Gtk.Notebook.NotebookChild w22 = ((global::Gtk.Notebook.NotebookChild)(this.notebook2 [this.table2]));
		w22.Position = 2;
		// Notebook tab
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("State");
		this.notebook2.SetTabLabel (this.table2, this.label1);
		this.label1.ShowAll ();
		this.vpaned1.Add (this.notebook2);
		global::Gtk.Paned.PanedChild w23 = ((global::Gtk.Paned.PanedChild)(this.vpaned1 [this.notebook2]));
		w23.Resize = false;
		// Container child vpaned1.Gtk.Paned+PanedChild
		this.notebook1 = new global::Gtk.Notebook ();
		this.notebook1.CanFocus = true;
		this.notebook1.Name = "notebook1";
		this.notebook1.CurrentPage = 0;
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.vbox3 = new global::Gtk.VBox ();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString (@"<ui><toolbar name='toolbar3'><toolitem name='goBackAction' action='goBackAction'/><toolitem name='goForwardAction' action='goForwardAction'/><separator/><toolitem name='deleteAction' action='deleteAction'/><toolitem name='openAction2' action='openAction2'/></toolbar></ui>");
		this.toolbar3 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget ("/toolbar3")));
		this.toolbar3.Name = "toolbar3";
		this.toolbar3.ShowArrow = false;
		this.toolbar3.ToolbarStyle = ((global::Gtk.ToolbarStyle)(0));
		this.toolbar3.IconSize = ((global::Gtk.IconSize)(2));
		this.vbox3.Add (this.toolbar3);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.toolbar3]));
		w24.Position = 0;
		w24.Expand = false;
		w24.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.image_snap = new global::Gtk.Image ();
		this.image_snap.Name = "image_snap";
		this.vbox3.Add (this.image_snap);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.image_snap]));
		w25.Position = 1;
		w25.Expand = false;
		w25.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.statusbar1 = new global::Gtk.Statusbar ();
		this.statusbar1.Name = "statusbar1";
		this.statusbar1.Spacing = 6;
		this.vbox3.Add (this.statusbar1);
		global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.statusbar1]));
		w26.Position = 2;
		w26.Expand = false;
		w26.Fill = false;
		this.notebook1.Add (this.vbox3);
		// Notebook tab
		this.label7 = new global::Gtk.Label ();
		this.label7.Name = "label7";
		this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("Snapshots");
		this.notebook1.SetTabLabel (this.vbox3, this.label7);
		this.label7.ShowAll ();
		this.vpaned1.Add (this.notebook1);
		this.hpaned1hpaned1.Add (this.vpaned1);
		this.hbox1.Add (this.hpaned1hpaned1);
		global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.hpaned1hpaned1]));
		w30.Position = 0;
		this.vbox1.Add (this.hbox1);
		global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
		w31.Position = 2;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 916;
		this.DefaultHeight = 594;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.openAction.Activated += new global::System.EventHandler (this.OnOpenActionActivated);
		this.quitAction.Activated += new global::System.EventHandler (this.OnQuitActionActivated);
		this.helpAction.Activated += new global::System.EventHandler (this.OnHelpActionActivated);
		this.AboutMyNesGTKAction.Activated += new global::System.EventHandler (this.OnAboutMyNesGTKActionActivated);
		this.VideoAction.Activated += new global::System.EventHandler (this.OnVideoActionActivated);
		this.AudioAction.Activated += new global::System.EventHandler (this.OnAudioActionActivated);
		this.PathsAction.Activated += new global::System.EventHandler (this.OnPathsActionActivated);
		this.PreferencesAction.Activated += new global::System.EventHandler (this.OnPreferencesActionActivated);
		this.openAction1.Activated += new global::System.EventHandler (this.OnOpenActionActivated);
		this.VideoSettingsAction.Activated += new global::System.EventHandler (this.OnVideoActionActivated);
		this.AudioSettingsAction.Activated += new global::System.EventHandler (this.OnAudioActionActivated);
		this.PathsSettingsAction.Activated += new global::System.EventHandler (this.OnPathsActionActivated);
		this.PreferencesAction1.Activated += new global::System.EventHandler (this.OnPreferencesActionActivated);
		this.helpAction1.Activated += new global::System.EventHandler (this.OnHelpActionActivated);
		this.AboutAction.Activated += new global::System.EventHandler (this.OnAboutMyNesGTKActionActivated);
		this.PaletteAction.Activated += new global::System.EventHandler (this.OnPaletteActionActivated);
		this.PaletteAction1.Activated += new global::System.EventHandler (this.OnPaletteActionActivated);
		this.InputAction.Activated += new global::System.EventHandler (this.OnInputActionActivated);
		this.InputAction1.Activated += new global::System.EventHandler (this.OnInputActionActivated);
		this.copyAction.Activated += new global::System.EventHandler (this.OnCopyActionActivated);
		this.saveAction.Activated += new global::System.EventHandler (this.OnSaveActionActivated);
		this.refreshAction.Activated += new global::System.EventHandler (this.OnRefreshActionActivated);
		this.goBackAction.Activated += new global::System.EventHandler (this.OnGoBackActionActivated);
		this.goForwardAction.Activated += new global::System.EventHandler (this.OnGoForwardActionActivated);
		this.openAction2.Activated += new global::System.EventHandler (this.OnOpenAction2Activated);
		this.PlayAction.Activated += new global::System.EventHandler (this.PlaySelected);
		this.StopAction.Activated += new global::System.EventHandler (this.StopSelected);
		this.StopSelectedAction.Activated += new global::System.EventHandler (this.StopSelected);
		this.deleteAction.Activated += new global::System.EventHandler (this.OnDeleteActionActivated);
		this.filechooserwidget2.FileActivated += new global::System.EventHandler (this.OnFilechooserwidget2FileActivated);
		this.filechooserwidget2.SelectionChanged += new global::System.EventHandler (this.OnFilechooserwidget2SelectionChanged);
		this.button4.Pressed += new global::System.EventHandler (this.OnButton4Pressed);
		this.button3.Pressed += new global::System.EventHandler (this.OnButton3Pressed);
		this.button2.Pressed += new global::System.EventHandler (this.OnButton2Pressed);
		this.button1.Pressed += new global::System.EventHandler (this.OnButton1Pressed);
		this.combobox_state.Changed += new global::System.EventHandler (this.OnComboboxStateChanged);
	}
}
