
// This file has been generated by the GUI designer. Do not modify.
public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	private global::Gtk.Action FileAction;
	private global::Gtk.Action openAction;
	private global::Gtk.Action SettingsAction;
	private global::Gtk.Action RenderersAction;
	private global::Gtk.Action VideoAction;
	private global::Gtk.Action SoundAction;
	private global::Gtk.Action PathsAction;
	private global::Gtk.Action quitAction;
	private global::Gtk.Action HelpAction;
	private global::Gtk.Action helpAction;
	private global::Gtk.Action AboutMyNesGTKAction;
	private global::Gtk.Action InputAction;
	private global::Gtk.Action ProfileAction;
	private global::Gtk.Action ConfigureAction;
	private global::Gtk.Action PaletteAction;
	private global::Gtk.Action EmulationSystemAction;
	private global::Gtk.Action EmulationAction;
	private global::Gtk.Action TogglePauseAction;
	private global::Gtk.Action TurnOffAction;
	private global::Gtk.Action HardResetAction;
	private global::Gtk.Action SoftResetAction;
	private global::Gtk.Action EmulationAction1;
	private global::Gtk.Action TogglePauseAction1;
	private global::Gtk.Action TurnOffAction1;
	private global::Gtk.Action HardResetAction1;
	private global::Gtk.Action SoftResetAction1;
	private global::Gtk.Action StateAction;
	private global::Gtk.Action SlotAction;
	private global::Gtk.RadioAction _0Action;
	private global::Gtk.RadioAction _1Action;
	private global::Gtk.RadioAction _2Action;
	private global::Gtk.RadioAction _3Action;
	private global::Gtk.RadioAction _4Action;
	private global::Gtk.RadioAction _5Action;
	private global::Gtk.RadioAction _6Action;
	private global::Gtk.RadioAction _7Action;
	private global::Gtk.RadioAction _8Action;
	private global::Gtk.RadioAction _9Action;
	private global::Gtk.Action saveAction;
	private global::Gtk.Action SaveAsAction;
	private global::Gtk.Action LoadAction;
	private global::Gtk.Action LoadAsAction;
	private global::Gtk.Action GameGenieAction;
	private global::Gtk.ToggleAction ActiveAction;
	private global::Gtk.Action ConfigureAction1;
	private global::Gtk.Action RecordSoundAction;
	private global::Gtk.Action RecorderAction;
	private global::Gtk.Action RecordSoundAction1;
	private global::Gtk.VBox vbox1;
	private global::Gtk.MenuBar menubar1;
	private global::Gtk.Image image1;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.FileAction = new global::Gtk.Action ("FileAction", "_File", null, null);
		this.FileAction.ShortLabel = "_File";
		w1.Add (this.FileAction, null);
		this.openAction = new global::Gtk.Action ("openAction", "_Open", null, "gtk-open");
		this.openAction.ShortLabel = "_Open";
		w1.Add (this.openAction, null);
		this.SettingsAction = new global::Gtk.Action ("SettingsAction", "_Settings", null, null);
		this.SettingsAction.ShortLabel = "_Settings";
		w1.Add (this.SettingsAction, null);
		this.RenderersAction = new global::Gtk.Action ("RenderersAction", "_Renderers", null, "renderers");
		this.RenderersAction.ShortLabel = "_Renderers";
		w1.Add (this.RenderersAction, null);
		this.VideoAction = new global::Gtk.Action ("VideoAction", "_Video", null, "tv");
		this.VideoAction.ShortLabel = "_Video";
		w1.Add (this.VideoAction, null);
		this.SoundAction = new global::Gtk.Action ("SoundAction", "_Sound", null, "sound");
		this.SoundAction.ShortLabel = "_Sound";
		w1.Add (this.SoundAction, null);
		this.PathsAction = new global::Gtk.Action ("PathsAction", "Paths", null, "pathsChange");
		this.PathsAction.ShortLabel = "Paths";
		w1.Add (this.PathsAction, null);
		this.quitAction = new global::Gtk.Action ("quitAction", "_Quit", null, "gtk-quit");
		this.quitAction.ShortLabel = "_Quit";
		w1.Add (this.quitAction, null);
		this.HelpAction = new global::Gtk.Action ("HelpAction", "_Help", null, null);
		this.HelpAction.ShortLabel = "_Help";
		w1.Add (this.HelpAction, null);
		this.helpAction = new global::Gtk.Action ("helpAction", "_Help", null, "gtk-help");
		this.helpAction.ShortLabel = "_Help";
		w1.Add (this.helpAction, null);
		this.AboutMyNesGTKAction = new global::Gtk.Action ("AboutMyNesGTKAction", "_About My Nes GTK", null, "MyNes");
		this.AboutMyNesGTKAction.ShortLabel = "_About My Nes GTK";
		w1.Add (this.AboutMyNesGTKAction, null);
		this.InputAction = new global::Gtk.Action ("InputAction", "_Input", null, "joystick");
		this.InputAction.ShortLabel = "_Input";
		w1.Add (this.InputAction, null);
		this.ProfileAction = new global::Gtk.Action ("ProfileAction", "_Profile", null, null);
		this.ProfileAction.ShortLabel = "_Profile";
		w1.Add (this.ProfileAction, null);
		this.ConfigureAction = new global::Gtk.Action ("ConfigureAction", "_Configure", null, null);
		this.ConfigureAction.ShortLabel = "_Configure";
		w1.Add (this.ConfigureAction, null);
		this.PaletteAction = new global::Gtk.Action ("PaletteAction", "_Palette", null, "palette");
		this.PaletteAction.ShortLabel = "_Palette";
		w1.Add (this.PaletteAction, null);
		this.EmulationSystemAction = new global::Gtk.Action ("EmulationSystemAction", "_Emulation system", null, null);
		this.EmulationSystemAction.ShortLabel = "_Emulation system";
		w1.Add (this.EmulationSystemAction, null);
		this.EmulationAction = new global::Gtk.Action ("EmulationAction", "_Emulation", null, null);
		this.EmulationAction.ShortLabel = "_Emulation";
		w1.Add (this.EmulationAction, null);
		this.TogglePauseAction = new global::Gtk.Action ("TogglePauseAction", "_Toggle pause", null, "togglePause");
		this.TogglePauseAction.ShortLabel = "_Toggle pause";
		w1.Add (this.TogglePauseAction, null);
		this.TurnOffAction = new global::Gtk.Action ("TurnOffAction", "Turn off", null, "turnOff");
		this.TurnOffAction.ShortLabel = "Turn off";
		w1.Add (this.TurnOffAction, null);
		this.HardResetAction = new global::Gtk.Action ("HardResetAction", "_Hard reset", null, "hardReset");
		this.HardResetAction.ShortLabel = "_Hard reset";
		w1.Add (this.HardResetAction, null);
		this.SoftResetAction = new global::Gtk.Action ("SoftResetAction", "_Soft reset", null, "softReset");
		this.SoftResetAction.ShortLabel = "_Soft reset";
		w1.Add (this.SoftResetAction, null);
		this.EmulationAction1 = new global::Gtk.Action ("EmulationAction1", "_Emulation", null, null);
		this.EmulationAction1.ShortLabel = "_Emulation";
		w1.Add (this.EmulationAction1, null);
		this.TogglePauseAction1 = new global::Gtk.Action ("TogglePauseAction1", "_Toggle pause", null, "togglePause");
		this.TogglePauseAction1.ShortLabel = "_Toggle pause";
		w1.Add (this.TogglePauseAction1, null);
		this.TurnOffAction1 = new global::Gtk.Action ("TurnOffAction1", "_Turn off", null, "turnOff");
		this.TurnOffAction1.ShortLabel = "_Turn off";
		w1.Add (this.TurnOffAction1, null);
		this.HardResetAction1 = new global::Gtk.Action ("HardResetAction1", "_Hard reset", null, "hardReset");
		this.HardResetAction1.ShortLabel = "_Hard reset";
		w1.Add (this.HardResetAction1, null);
		this.SoftResetAction1 = new global::Gtk.Action ("SoftResetAction1", "_Soft reset", null, "softReset");
		this.SoftResetAction1.ShortLabel = "_Soft reset";
		w1.Add (this.SoftResetAction1, null);
		this.StateAction = new global::Gtk.Action ("StateAction", "_State", null, null);
		this.StateAction.ShortLabel = "_State";
		w1.Add (this.StateAction, null);
		this.SlotAction = new global::Gtk.Action ("SlotAction", "Slot", null, null);
		this.SlotAction.ShortLabel = "Slot";
		w1.Add (this.SlotAction, null);
		this._0Action = new global::Gtk.RadioAction ("_0Action", "0", null, null, 0);
		this._0Action.Group = new global::GLib.SList (global::System.IntPtr.Zero);
		this._0Action.ShortLabel = "0";
		w1.Add (this._0Action, null);
		this._1Action = new global::Gtk.RadioAction ("_1Action", "1", null, null, 0);
		this._1Action.Group = this._0Action.Group;
		this._1Action.ShortLabel = "1";
		w1.Add (this._1Action, null);
		this._2Action = new global::Gtk.RadioAction ("_2Action", "2", null, null, 0);
		this._2Action.Group = this._0Action.Group;
		this._2Action.ShortLabel = "2";
		w1.Add (this._2Action, null);
		this._3Action = new global::Gtk.RadioAction ("_3Action", "3", null, null, 0);
		this._3Action.Group = this._0Action.Group;
		this._3Action.ShortLabel = "3";
		w1.Add (this._3Action, null);
		this._4Action = new global::Gtk.RadioAction ("_4Action", "4", null, null, 0);
		this._4Action.Group = this._3Action.Group;
		this._4Action.ShortLabel = "4";
		w1.Add (this._4Action, null);
		this._5Action = new global::Gtk.RadioAction ("_5Action", "5", null, null, 0);
		this._5Action.Group = this._3Action.Group;
		this._5Action.ShortLabel = "5";
		w1.Add (this._5Action, null);
		this._6Action = new global::Gtk.RadioAction ("_6Action", "6", null, null, 0);
		this._6Action.Group = this._3Action.Group;
		this._6Action.ShortLabel = "6";
		w1.Add (this._6Action, null);
		this._7Action = new global::Gtk.RadioAction ("_7Action", "7", null, null, 0);
		this._7Action.Group = this._3Action.Group;
		this._7Action.ShortLabel = "7";
		w1.Add (this._7Action, null);
		this._8Action = new global::Gtk.RadioAction ("_8Action", "8", null, null, 0);
		this._8Action.Group = this._3Action.Group;
		this._8Action.ShortLabel = "8";
		w1.Add (this._8Action, null);
		this._9Action = new global::Gtk.RadioAction ("_9Action", "9", null, null, 0);
		this._9Action.Group = this._3Action.Group;
		this._9Action.ShortLabel = "9";
		w1.Add (this._9Action, null);
		this.saveAction = new global::Gtk.Action ("saveAction", "_Save", null, "gtk-save");
		this.saveAction.ShortLabel = "_Save";
		w1.Add (this.saveAction, null);
		this.SaveAsAction = new global::Gtk.Action ("SaveAsAction", "Save as", null, null);
		this.SaveAsAction.ShortLabel = "Save as";
		w1.Add (this.SaveAsAction, null);
		this.LoadAction = new global::Gtk.Action ("LoadAction", "_Load", null, null);
		this.LoadAction.ShortLabel = "_Load";
		w1.Add (this.LoadAction, null);
		this.LoadAsAction = new global::Gtk.Action ("LoadAsAction", "Load as", null, null);
		this.LoadAsAction.ShortLabel = "Load as";
		w1.Add (this.LoadAsAction, null);
		this.GameGenieAction = new global::Gtk.Action ("GameGenieAction", "Game Genie", null, null);
		this.GameGenieAction.ShortLabel = "Game Genie";
		w1.Add (this.GameGenieAction, null);
		this.ActiveAction = new global::Gtk.ToggleAction ("ActiveAction", "_Active", null, null);
		this.ActiveAction.ShortLabel = "_Active";
		w1.Add (this.ActiveAction, null);
		this.ConfigureAction1 = new global::Gtk.Action ("ConfigureAction1", "_Configure", null, "gg");
		this.ConfigureAction1.ShortLabel = "_Configure";
		w1.Add (this.ConfigureAction1, null);
		this.RecordSoundAction = new global::Gtk.Action ("RecordSoundAction", "Record sound", null, null);
		this.RecordSoundAction.ShortLabel = "Record sound";
		w1.Add (this.RecordSoundAction, null);
		this.RecorderAction = new global::Gtk.Action ("RecorderAction", "_Recorder", null, null);
		this.RecorderAction.ShortLabel = "_Recorder";
		w1.Add (this.RecorderAction, null);
		this.RecordSoundAction1 = new global::Gtk.Action ("RecordSoundAction1", "_Record sound", null, null);
		this.RecordSoundAction1.ShortLabel = "_Record sound";
		w1.Add (this.RecordSoundAction1, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = "My Nes GTK";
		this.Icon = global::Gdk.Pixbuf.LoadFromResource ("MyNesGTK.MyNes.ico");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.Resizable = false;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><menubar name=\'menubar1\'><menu name=\'FileAction\' action=\'FileAction\'><menuite" +
			"m name=\'openAction\' action=\'openAction\'/><menuitem name=\'quitAction\' action=\'qui" +
			"tAction\'/></menu><menu name=\'EmulationAction1\' action=\'EmulationAction1\'><menuit" +
			"em name=\'TogglePauseAction1\' action=\'TogglePauseAction1\'/><menuitem name=\'TurnOf" +
			"fAction1\' action=\'TurnOffAction1\'/><menuitem name=\'HardResetAction1\' action=\'Har" +
			"dResetAction1\'/><menuitem name=\'SoftResetAction1\' action=\'SoftResetAction1\'/></m" +
			"enu><menu name=\'StateAction\' action=\'StateAction\'><menu name=\'SlotAction\' action" +
			"=\'SlotAction\'><menuitem name=\'_0Action\' action=\'_0Action\'/><menuitem name=\'_1Act" +
			"ion\' action=\'_1Action\'/><menuitem name=\'_2Action\' action=\'_2Action\'/><menuitem n" +
			"ame=\'_3Action\' action=\'_3Action\'/><menuitem name=\'_4Action\' action=\'_4Action\'/><" +
			"menuitem name=\'_5Action\' action=\'_5Action\'/><menuitem name=\'_6Action\' action=\'_6" +
			"Action\'/><menuitem name=\'_7Action\' action=\'_7Action\'/><menuitem name=\'_8Action\' " +
			"action=\'_8Action\'/><menuitem name=\'_9Action\' action=\'_9Action\'/></menu><menuitem" +
			" name=\'saveAction\' action=\'saveAction\'/><menuitem name=\'SaveAsAction\' action=\'Sa" +
			"veAsAction\'/><menuitem name=\'LoadAction\' action=\'LoadAction\'/><menuitem name=\'Lo" +
			"adAsAction\' action=\'LoadAsAction\'/></menu><menu name=\'GameGenieAction\' action=\'G" +
			"ameGenieAction\'><menuitem name=\'ActiveAction\' action=\'ActiveAction\'/><menuitem n" +
			"ame=\'ConfigureAction1\' action=\'ConfigureAction1\'/></menu><menu name=\'RecorderAct" +
			"ion\' action=\'RecorderAction\'><menuitem name=\'RecordSoundAction1\' action=\'RecordS" +
			"oundAction1\'/></menu><menu name=\'SettingsAction\' action=\'SettingsAction\'><menuit" +
			"em name=\'RenderersAction\' action=\'RenderersAction\'/><menuitem name=\'VideoAction\'" +
			" action=\'VideoAction\'/><menuitem name=\'SoundAction\' action=\'SoundAction\'/><menui" +
			"tem name=\'PathsAction\' action=\'PathsAction\'/><menuitem name=\'InputAction\' action" +
			"=\'InputAction\'/><menuitem name=\'PaletteAction\' action=\'PaletteAction\'/><menuitem" +
			" name=\'EmulationSystemAction\' action=\'EmulationSystemAction\'/></menu><menu name=" +
			"\'HelpAction\' action=\'HelpAction\'><menuitem name=\'helpAction\' action=\'helpAction\'" +
			"/><menuitem name=\'AboutMyNesGTKAction\' action=\'AboutMyNesGTKAction\'/></menu></me" +
			"nubar></ui>");
		this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar1")));
		this.menubar1.Name = "menubar1";
		this.vbox1.Add (this.menubar1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.menubar1]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.image1 = new global::Gtk.Image ();
		this.image1.Name = "image1";
		this.image1.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("MyNesGTK.MyNes.png");
		this.vbox1.Add (this.image1);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.image1]));
		w3.Position = 1;
		w3.Expand = false;
		w3.Fill = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 659;
		this.DefaultHeight = 291;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.openAction.Activated += new global::System.EventHandler (this.OnOpenActionActivated);
		this.RenderersAction.Activated += new global::System.EventHandler (this.OnRenderersActionActivated);
		this.VideoAction.Activated += new global::System.EventHandler (this.OnVideoAction1Activated);
		this.SoundAction.Activated += new global::System.EventHandler (this.OnSoundActionActivated);
		this.PathsAction.Activated += new global::System.EventHandler (this.OnPathsActionActivated);
		this.quitAction.Activated += new global::System.EventHandler (this.OnQuitActionActivated);
		this.helpAction.Activated += new global::System.EventHandler (this.OnHelpActionActivated);
		this.AboutMyNesGTKAction.Activated += new global::System.EventHandler (this.OnAboutMyNesGTKActionActivated);
		this.InputAction.Activated += new global::System.EventHandler (this.OnConfigureActionActivated);
		this.ConfigureAction.Activated += new global::System.EventHandler (this.OnConfigureActionActivated);
		this.PaletteAction.Activated += new global::System.EventHandler (this.OnPaletteActionActivated);
		this.EmulationSystemAction.Activated += new global::System.EventHandler (this.OnEmulationSystemActionActivated);
		this.TogglePauseAction1.Activated += new global::System.EventHandler (this.OnTogglePauseActionActivated);
		this.TurnOffAction1.Activated += new global::System.EventHandler (this.OnTurnOffAction1Activated);
		this.HardResetAction1.Activated += new global::System.EventHandler (this.OnHardResetAction1Activated);
		this.SoftResetAction1.Activated += new global::System.EventHandler (this.OnSoftResetAction1Activated);
		this._0Action.Activated += new global::System.EventHandler (this.On0ActionActivated);
		this._1Action.Activated += new global::System.EventHandler (this.On1ActionActivated);
		this._2Action.Activated += new global::System.EventHandler (this.On2ActionActivated);
		this._3Action.Activated += new global::System.EventHandler (this.On3ActionActivated);
		this._4Action.Activated += new global::System.EventHandler (this.On4ActionActivated);
		this._5Action.Activated += new global::System.EventHandler (this.On5ActionActivated);
		this._6Action.Activated += new global::System.EventHandler (this.On6ActionActivated);
		this._7Action.Activated += new global::System.EventHandler (this.On7ActionActivated);
		this._8Action.Activated += new global::System.EventHandler (this.On8ActionActivated);
		this._9Action.Activated += new global::System.EventHandler (this.On9ActionActivated);
		this.saveAction.Activated += new global::System.EventHandler (this.OnSaveActionActivated);
		this.SaveAsAction.Activated += new global::System.EventHandler (this.OnSaveAsActionActivated);
		this.LoadAction.Activated += new global::System.EventHandler (this.OnLoadActionActivated);
		this.LoadAsAction.Activated += new global::System.EventHandler (this.OnLoadAsActionActivated);
		this.ActiveAction.Activated += new global::System.EventHandler (this.OnActiveActionActivated);
		this.ConfigureAction1.Activated += new global::System.EventHandler (this.OnConfigureAction1Activated);
		this.RecordSoundAction1.Activated += new global::System.EventHandler (this.OnRecordSoundAction1Activated);
	}
}
