
// This file has been generated by the GUI designer. Do not modify.
namespace MyNesGTK
{
	public partial class Dialog_SoundSettings
	{
		private global::Gtk.Table table3;
		private global::Gtk.Button button9;
		private global::Gtk.CheckButton checkbutton_soundEnabled;
		private global::Gtk.ComboBox combobox1;
		private global::Gtk.HScale hscale_delay;
		private global::Gtk.HScale hscale_vol;
		private global::Gtk.Label label_delay;
		private global::Gtk.Label label_vol;
		private global::Gtk.Label label10;
		private global::Gtk.Label label11;
		private global::Gtk.Label label6;
		private global::Gtk.Label label8;
		private global::Gtk.Button buttonCancel;
		private global::Gtk.Button buttonOk;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MyNesGTK.Dialog_SoundSettings
			this.Name = "MyNesGTK.Dialog_SoundSettings";
			this.Title = "Sound settings";
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child MyNesGTK.Dialog_SoundSettings.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.table3 = new global::Gtk.Table (((uint)(5)), ((uint)(3)), false);
			this.table3.Name = "table3";
			this.table3.RowSpacing = ((uint)(6));
			this.table3.ColumnSpacing = ((uint)(6));
			// Container child table3.Gtk.Table+TableChild
			this.button9 = new global::Gtk.Button ();
			this.button9.CanFocus = true;
			this.button9.Name = "button9";
			this.button9.UseUnderline = true;
			this.button9.Label = "Defaults";
			this.table3.Add (this.button9);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table3 [this.button9]));
			w2.TopAttach = ((uint)(4));
			w2.BottomAttach = ((uint)(5));
			w2.XOptions = ((global::Gtk.AttachOptions)(4));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.checkbutton_soundEnabled = new global::Gtk.CheckButton ();
			this.checkbutton_soundEnabled.CanFocus = true;
			this.checkbutton_soundEnabled.Name = "checkbutton_soundEnabled";
			this.checkbutton_soundEnabled.Label = "Sound enabled";
			this.checkbutton_soundEnabled.DrawIndicator = true;
			this.checkbutton_soundEnabled.UseUnderline = true;
			this.table3.Add (this.checkbutton_soundEnabled);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table3 [this.checkbutton_soundEnabled]));
			w3.RightAttach = ((uint)(2));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.combobox1 = global::Gtk.ComboBox.NewText ();
			this.combobox1.Name = "combobox1";
			this.table3.Add (this.combobox1);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table3 [this.combobox1]));
			w4.TopAttach = ((uint)(3));
			w4.BottomAttach = ((uint)(4));
			w4.LeftAttach = ((uint)(1));
			w4.RightAttach = ((uint)(2));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.hscale_delay = new global::Gtk.HScale (null);
			this.hscale_delay.CanFocus = true;
			this.hscale_delay.Name = "hscale_delay";
			this.hscale_delay.Adjustment.Lower = 1D;
			this.hscale_delay.Adjustment.Upper = 100D;
			this.hscale_delay.Adjustment.PageIncrement = 10D;
			this.hscale_delay.Adjustment.StepIncrement = 1D;
			this.hscale_delay.DrawValue = false;
			this.hscale_delay.Digits = 0;
			this.hscale_delay.ValuePos = ((global::Gtk.PositionType)(2));
			this.table3.Add (this.hscale_delay);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table3 [this.hscale_delay]));
			w5.TopAttach = ((uint)(2));
			w5.BottomAttach = ((uint)(3));
			w5.LeftAttach = ((uint)(1));
			w5.RightAttach = ((uint)(2));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.hscale_vol = new global::Gtk.HScale (null);
			this.hscale_vol.CanFocus = true;
			this.hscale_vol.Name = "hscale_vol";
			this.hscale_vol.Adjustment.Lower = -3000D;
			this.hscale_vol.Adjustment.Upper = 100D;
			this.hscale_vol.Adjustment.PageIncrement = 10D;
			this.hscale_vol.Adjustment.StepIncrement = 1D;
			this.hscale_vol.Adjustment.Value = -500D;
			this.hscale_vol.DrawValue = false;
			this.hscale_vol.Digits = 0;
			this.hscale_vol.ValuePos = ((global::Gtk.PositionType)(2));
			this.table3.Add (this.hscale_vol);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table3 [this.hscale_vol]));
			w6.TopAttach = ((uint)(1));
			w6.BottomAttach = ((uint)(2));
			w6.LeftAttach = ((uint)(1));
			w6.RightAttach = ((uint)(2));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.label_delay = new global::Gtk.Label ();
			this.label_delay.Name = "label_delay";
			this.label_delay.LabelProp = "50 ms";
			this.table3.Add (this.label_delay);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table3 [this.label_delay]));
			w7.TopAttach = ((uint)(2));
			w7.BottomAttach = ((uint)(3));
			w7.LeftAttach = ((uint)(2));
			w7.RightAttach = ((uint)(3));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.label_vol = new global::Gtk.Label ();
			this.label_vol.Name = "label_vol";
			this.label_vol.LabelProp = "70 %";
			this.table3.Add (this.label_vol);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table3 [this.label_vol]));
			w8.TopAttach = ((uint)(1));
			w8.BottomAttach = ((uint)(2));
			w8.LeftAttach = ((uint)(2));
			w8.RightAttach = ((uint)(3));
			w8.XOptions = ((global::Gtk.AttachOptions)(4));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.label10 = new global::Gtk.Label ();
			this.label10.Name = "label10";
			this.label10.LabelProp = "Frequency: ";
			this.table3.Add (this.label10);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table3 [this.label10]));
			w9.TopAttach = ((uint)(3));
			w9.BottomAttach = ((uint)(4));
			w9.XOptions = ((global::Gtk.AttachOptions)(4));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.label11 = new global::Gtk.Label ();
			this.label11.Name = "label11";
			this.label11.LabelProp = "Hz, 16 bit.";
			this.table3.Add (this.label11);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table3 [this.label11]));
			w10.TopAttach = ((uint)(3));
			w10.BottomAttach = ((uint)(4));
			w10.LeftAttach = ((uint)(2));
			w10.RightAttach = ((uint)(3));
			w10.XOptions = ((global::Gtk.AttachOptions)(4));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.label6 = new global::Gtk.Label ();
			this.label6.Name = "label6";
			this.label6.LabelProp = "Volume: ";
			this.table3.Add (this.label6);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table3 [this.label6]));
			w11.TopAttach = ((uint)(1));
			w11.BottomAttach = ((uint)(2));
			w11.XOptions = ((global::Gtk.AttachOptions)(4));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.label8 = new global::Gtk.Label ();
			this.label8.Name = "label8";
			this.label8.LabelProp = "Delay: ";
			this.table3.Add (this.label8);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table3 [this.label8]));
			w12.TopAttach = ((uint)(2));
			w12.BottomAttach = ((uint)(3));
			w12.XOptions = ((global::Gtk.AttachOptions)(4));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			w1.Add (this.table3);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(w1 [this.table3]));
			w13.Position = 0;
			w13.Expand = false;
			w13.Fill = false;
			// Internal child MyNesGTK.Dialog_SoundSettings.ActionArea
			global::Gtk.HButtonBox w14 = this.ActionArea;
			w14.Name = "dialog1_ActionArea";
			w14.Spacing = 10;
			w14.BorderWidth = ((uint)(5));
			w14.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget (this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w15 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w14 [this.buttonCancel]));
			w15.Expand = false;
			w15.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button ();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			this.AddActionWidget (this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w16 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w14 [this.buttonOk]));
			w16.Position = 1;
			w16.Expand = false;
			w16.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 358;
			this.DefaultHeight = 260;
			this.Show ();
			this.hscale_vol.ValueChanged += new global::System.EventHandler (this.OnHscaleVolValueChanged);
			this.hscale_delay.ValueChanged += new global::System.EventHandler (this.OnHscaleDelayValueChanged);
			this.button9.Clicked += new global::System.EventHandler (this.OnButton9Clicked);
		}
	}
}
