
// This file has been generated by the GUI designer. Do not modify.
namespace MyNesGTK
{
	public partial class Dialog_Audio
	{
		private global::Gtk.Table table1;
		
		private global::Gtk.Button button162;
		
		private global::Gtk.CheckButton checkbutton_dmc;
		
		private global::Gtk.CheckButton checkbutton_enablePlayback;
		
		private global::Gtk.CheckButton checkbutton_noz;
		
		private global::Gtk.CheckButton checkbutton_sq1;
		
		private global::Gtk.CheckButton checkbutton_sq2;
		
		private global::Gtk.CheckButton checkbutton_trl;
		
		private global::Gtk.ComboBox combobox_fequency;
		
		private global::Gtk.HScale hscale_volume;
		
		private global::Gtk.Label label1;
		
		private global::Gtk.Label label2;
		
		private global::Gtk.Button buttonCancel;
		
		private global::Gtk.Button buttonOk;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MyNesGTK.Dialog_Audio
			this.Name = "MyNesGTK.Dialog_Audio";
			this.Title = global::Mono.Unix.Catalog.GetString ("Audio Settings");
			this.Icon = global::Gdk.Pixbuf.LoadFromResource ("MyNesGTK.resources.sound.png");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Modal = true;
			// Internal child MyNesGTK.Dialog_Audio.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.table1 = new global::Gtk.Table (((uint)(9)), ((uint)(2)), true);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.button162 = new global::Gtk.Button ();
			this.button162.CanFocus = true;
			this.button162.Name = "button162";
			this.button162.UseUnderline = true;
			this.button162.Label = global::Mono.Unix.Catalog.GetString ("Reset to defaults");
			this.table1.Add (this.button162);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table1 [this.button162]));
			w2.TopAttach = ((uint)(8));
			w2.BottomAttach = ((uint)(9));
			w2.XOptions = ((global::Gtk.AttachOptions)(4));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.checkbutton_dmc = new global::Gtk.CheckButton ();
			this.checkbutton_dmc.CanFocus = true;
			this.checkbutton_dmc.Name = "checkbutton_dmc";
			this.checkbutton_dmc.Label = global::Mono.Unix.Catalog.GetString ("Channel DMC Enabled");
			this.checkbutton_dmc.DrawIndicator = true;
			this.checkbutton_dmc.UseUnderline = true;
			this.table1.Add (this.checkbutton_dmc);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table1 [this.checkbutton_dmc]));
			w3.TopAttach = ((uint)(7));
			w3.BottomAttach = ((uint)(8));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.checkbutton_enablePlayback = new global::Gtk.CheckButton ();
			this.checkbutton_enablePlayback.CanFocus = true;
			this.checkbutton_enablePlayback.Name = "checkbutton_enablePlayback";
			this.checkbutton_enablePlayback.Label = global::Mono.Unix.Catalog.GetString ("Audio playback enabled");
			this.checkbutton_enablePlayback.DrawIndicator = true;
			this.checkbutton_enablePlayback.UseUnderline = true;
			this.table1.Add (this.checkbutton_enablePlayback);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1 [this.checkbutton_enablePlayback]));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.checkbutton_noz = new global::Gtk.CheckButton ();
			this.checkbutton_noz.CanFocus = true;
			this.checkbutton_noz.Name = "checkbutton_noz";
			this.checkbutton_noz.Label = global::Mono.Unix.Catalog.GetString ("Channel Noise Enabled");
			this.checkbutton_noz.DrawIndicator = true;
			this.checkbutton_noz.UseUnderline = true;
			this.table1.Add (this.checkbutton_noz);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table1 [this.checkbutton_noz]));
			w5.TopAttach = ((uint)(5));
			w5.BottomAttach = ((uint)(6));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.checkbutton_sq1 = new global::Gtk.CheckButton ();
			this.checkbutton_sq1.CanFocus = true;
			this.checkbutton_sq1.Name = "checkbutton_sq1";
			this.checkbutton_sq1.Label = global::Mono.Unix.Catalog.GetString ("Channel Square 1 Enabled");
			this.checkbutton_sq1.DrawIndicator = true;
			this.checkbutton_sq1.UseUnderline = true;
			this.table1.Add (this.checkbutton_sq1);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table1 [this.checkbutton_sq1]));
			w6.TopAttach = ((uint)(3));
			w6.BottomAttach = ((uint)(4));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.checkbutton_sq2 = new global::Gtk.CheckButton ();
			this.checkbutton_sq2.CanFocus = true;
			this.checkbutton_sq2.Name = "checkbutton_sq2";
			this.checkbutton_sq2.Label = global::Mono.Unix.Catalog.GetString ("Channel Square 2 Enabled");
			this.checkbutton_sq2.DrawIndicator = true;
			this.checkbutton_sq2.UseUnderline = true;
			this.table1.Add (this.checkbutton_sq2);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table1 [this.checkbutton_sq2]));
			w7.TopAttach = ((uint)(4));
			w7.BottomAttach = ((uint)(5));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.checkbutton_trl = new global::Gtk.CheckButton ();
			this.checkbutton_trl.CanFocus = true;
			this.checkbutton_trl.Name = "checkbutton_trl";
			this.checkbutton_trl.Label = global::Mono.Unix.Catalog.GetString ("Channel Triangle Enabled");
			this.checkbutton_trl.DrawIndicator = true;
			this.checkbutton_trl.UseUnderline = true;
			this.table1.Add (this.checkbutton_trl);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table1 [this.checkbutton_trl]));
			w8.TopAttach = ((uint)(6));
			w8.BottomAttach = ((uint)(7));
			w8.XOptions = ((global::Gtk.AttachOptions)(4));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.combobox_fequency = global::Gtk.ComboBox.NewText ();
			this.combobox_fequency.AppendText (global::Mono.Unix.Catalog.GetString ("44100"));
			this.combobox_fequency.AppendText (global::Mono.Unix.Catalog.GetString ("48000"));
			this.combobox_fequency.Name = "combobox_fequency";
			this.combobox_fequency.Active = 0;
			this.table1.Add (this.combobox_fequency);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table1 [this.combobox_fequency]));
			w9.TopAttach = ((uint)(2));
			w9.BottomAttach = ((uint)(3));
			w9.LeftAttach = ((uint)(1));
			w9.RightAttach = ((uint)(2));
			w9.XOptions = ((global::Gtk.AttachOptions)(4));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.hscale_volume = new global::Gtk.HScale (null);
			this.hscale_volume.CanFocus = true;
			this.hscale_volume.Name = "hscale_volume";
			this.hscale_volume.Adjustment.Upper = 100D;
			this.hscale_volume.Adjustment.PageIncrement = 10D;
			this.hscale_volume.Adjustment.StepIncrement = 1D;
			this.hscale_volume.Adjustment.Value = 100D;
			this.hscale_volume.DrawValue = true;
			this.hscale_volume.Digits = 0;
			this.hscale_volume.ValuePos = ((global::Gtk.PositionType)(2));
			this.table1.Add (this.hscale_volume);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table1 [this.hscale_volume]));
			w10.TopAttach = ((uint)(1));
			w10.BottomAttach = ((uint)(2));
			w10.LeftAttach = ((uint)(1));
			w10.RightAttach = ((uint)(2));
			w10.XOptions = ((global::Gtk.AttachOptions)(4));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Volume");
			this.table1.Add (this.label1);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table1 [this.label1]));
			w11.TopAttach = ((uint)(1));
			w11.BottomAttach = ((uint)(2));
			w11.XOptions = ((global::Gtk.AttachOptions)(4));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Frequency");
			this.table1.Add (this.label2);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table1 [this.label2]));
			w12.TopAttach = ((uint)(2));
			w12.BottomAttach = ((uint)(3));
			w12.XOptions = ((global::Gtk.AttachOptions)(4));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			w1.Add (this.table1);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(w1 [this.table1]));
			w13.Position = 0;
			w13.Expand = false;
			w13.Fill = false;
			// Internal child MyNesGTK.Dialog_Audio.ActionArea
			global::Gtk.HButtonBox w14 = this.ActionArea;
			w14.Name = "dialog1_ActionArea";
			w14.Spacing = 10;
			w14.BorderWidth = ((uint)(5));
			w14.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget (this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w15 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w14 [this.buttonCancel]));
			w15.Expand = false;
			w15.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button ();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			this.AddActionWidget (this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w16 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w14 [this.buttonOk]));
			w16.Position = 1;
			w16.Expand = false;
			w16.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 456;
			this.DefaultHeight = 475;
			this.Show ();
			this.button162.Pressed += new global::System.EventHandler (this.OnButton162Pressed);
		}
	}
}
