//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyNes.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10, 10")]
        public global::System.Drawing.Point WinLocation {
            get {
                return ((global::System.Drawing.Point)(this["WinLocation"]));
            }
            set {
                this["WinLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("528, 511")]
        public global::System.Drawing.Size WinSize {
            get {
                return ((global::System.Drawing.Size)(this["WinSize"]));
            }
            set {
                this["WinSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Audio_SoundEnabled {
            get {
                return ((bool)(this["Audio_SoundEnabled"]));
            }
            set {
                this["Audio_SoundEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("44100")]
        public int Audio_Frequency {
            get {
                return ((int)(this["Audio_Frequency"]));
            }
            set {
                this["Audio_Frequency"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16")]
        public short Audio_BitsPerSample {
            get {
                return ((short)(this["Audio_BitsPerSample"]));
            }
            set {
                this["Audio_BitsPerSample"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MyNesDatabase.mndb")]
        public string Database_FilePath {
            get {
                return ((string)(this["Database_FilePath"]));
            }
            set {
                this["Database_FilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection Database_FoldersScanned {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Database_FoldersScanned"]));
            }
            set {
                this["Database_FoldersScanned"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10, 10")]
        public global::System.Drawing.Point LauncherLocation {
            get {
                return ((global::System.Drawing.Point)(this["LauncherLocation"]));
            }
            set {
                this["LauncherLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("994, 617")]
        public global::System.Drawing.Size LauncherSize {
            get {
                return ((global::System.Drawing.Size)(this["LauncherSize"]));
            }
            set {
                this["LauncherSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection Database_FoldersSnapshots {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Database_FoldersSnapshots"]));
            }
            set {
                this["Database_FoldersSnapshots"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection Database_FoldersCovers {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Database_FoldersCovers"]));
            }
            set {
                this["Database_FoldersCovers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection Database_FoldersInfos {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Database_FoldersInfos"]));
            }
            set {
                this["Database_FoldersInfos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection Database_FoldersManuals {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Database_FoldersManuals"]));
            }
            set {
                this["Database_FoldersManuals"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("StretchIfLarger")]
        public global::MyNes.ImageViewMode SnapsView_ImageMode {
            get {
                return ((global::MyNes.ImageViewMode)(this["SnapsView_ImageMode"]));
            }
            set {
                this["SnapsView_ImageMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("StretchIfLarger")]
        public global::MyNes.ImageViewMode CoversView_ImageMode {
            get {
                return ((global::MyNes.ImageViewMode)(this["CoversView_ImageMode"]));
            }
            set {
                this["CoversView_ImageMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SnapsView_ShowBar {
            get {
                return ((bool)(this["SnapsView_ShowBar"]));
            }
            set {
                this["SnapsView_ShowBar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SnapsView_ShowStatus {
            get {
                return ((bool)(this["SnapsView_ShowStatus"]));
            }
            set {
                this["SnapsView_ShowStatus"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CoversView_ShowBar {
            get {
                return ((bool)(this["CoversView_ShowBar"]));
            }
            set {
                this["CoversView_ShowBar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CoversView_ShowStatus {
            get {
                return ((bool)(this["CoversView_ShowStatus"]));
            }
            set {
                this["CoversView_ShowStatus"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("659")]
        public int LauncherSpliter1 {
            get {
                return ((int)(this["LauncherSpliter1"]));
            }
            set {
                this["LauncherSpliter1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("259")]
        public int LauncherSpliter2 {
            get {
                return ((int)(this["LauncherSpliter2"]));
            }
            set {
                this["LauncherSpliter2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LauncherAutoMinimize {
            get {
                return ((bool)(this["LauncherAutoMinimize"]));
            }
            set {
                this["LauncherAutoMinimize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LauncherAutoCycleImagesInGameTab {
            get {
                return ((bool)(this["LauncherAutoCycleImagesInGameTab"]));
            }
            set {
                this["LauncherAutoCycleImagesInGameTab"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LauncherRememberLastSelection {
            get {
                return ((bool)(this["LauncherRememberLastSelection"]));
            }
            set {
                this["LauncherRememberLastSelection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LauncherLatestSelection {
            get {
                return ((int)(this["LauncherLatestSelection"]));
            }
            set {
                this["LauncherLatestSelection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LauncherShowAyAppStart {
            get {
                return ((bool)(this["LauncherShowAyAppStart"]));
            }
            set {
                this["LauncherShowAyAppStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Folder_State {
            get {
                return ((string)(this["Folder_State"]));
            }
            set {
                this["Folder_State"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Folder_Sram {
            get {
                return ((string)(this["Folder_Sram"]));
            }
            set {
                this["Folder_Sram"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FirstRun {
            get {
                return ((bool)(this["FirstRun"]));
            }
            set {
                this["FirstRun"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SaveSramOnShutdown {
            get {
                return ((bool)(this["SaveSramOnShutdown"]));
            }
            set {
                this["SaveSramOnShutdown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int Video_StretchMulti {
            get {
                return ((int)(this["Video_StretchMulti"]));
            }
            set {
                this["Video_StretchMulti"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Video_StretchToMulti {
            get {
                return ((bool)(this["Video_StretchToMulti"]));
            }
            set {
                this["Video_StretchToMulti"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Video_StartFullscreen {
            get {
                return ((bool)(this["Video_StartFullscreen"]));
            }
            set {
                this["Video_StartFullscreen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Video_FullscreenRes {
            get {
                return ((int)(this["Video_FullscreenRes"]));
            }
            set {
                this["Video_FullscreenRes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Video_ShowNotifications {
            get {
                return ((bool)(this["Video_ShowNotifications"]));
            }
            set {
                this["Video_ShowNotifications"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Video_ShowFPS {
            get {
                return ((bool)(this["Video_ShowFPS"]));
            }
            set {
                this["Video_ShowFPS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Video_CutLines {
            get {
                return ((bool)(this["Video_CutLines"]));
            }
            set {
                this["Video_CutLines"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Video_HardwareVertexProcessing {
            get {
                return ((bool)(this["Video_HardwareVertexProcessing"]));
            }
            set {
                this["Video_HardwareVertexProcessing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Video_KeepAspectRatio {
            get {
                return ((bool)(this["Video_KeepAspectRatio"]));
            }
            set {
                this["Video_KeepAspectRatio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Point")]
        public global::SlimDX.Direct3D9.TextureFilter Video_Filter {
            get {
                return ((global::SlimDX.Direct3D9.TextureFilter)(this["Video_Filter"]));
            }
            set {
                this["Video_Filter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int Audio_LatencyInMilliseconds {
            get {
                return ((int)(this["Audio_LatencyInMilliseconds"]));
            }
            set {
                this["Audio_LatencyInMilliseconds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int Audio_Volume {
            get {
                return ((int)(this["Audio_Volume"]));
            }
            set {
                this["Audio_Volume"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PauseAtFocusLost {
            get {
                return ((bool)(this["PauseAtFocusLost"]));
            }
            set {
                this["PauseAtFocusLost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".png")]
        public string SnapshotFormat {
            get {
                return ((string)(this["SnapshotFormat"]));
            }
            set {
                this["SnapshotFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Folder_Snapshots {
            get {
                return ((string)(this["Folder_Snapshots"]));
            }
            set {
                this["Folder_Snapshots"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ReplaceSnapshot {
            get {
                return ((bool)(this["ReplaceSnapshot"]));
            }
            set {
                this["ReplaceSnapshot"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::MyNes.ControlMappingSettings ControlSettings {
            get {
                return ((global::MyNes.ControlMappingSettings)(this["ControlSettings"]));
            }
            set {
                this["ControlSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.07")]
        public float Palette_NTSC_brightness {
            get {
                return ((float)(this["Palette_NTSC_brightness"]));
            }
            set {
                this["Palette_NTSC_brightness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.2")]
        public float Palette_NTSC_contrast {
            get {
                return ((float)(this["Palette_NTSC_contrast"]));
            }
            set {
                this["Palette_NTSC_contrast"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.8")]
        public float Palette_NTSC_gamma {
            get {
                return ((float)(this["Palette_NTSC_gamma"]));
            }
            set {
                this["Palette_NTSC_gamma"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float Palette_NTSC_hue_tweak {
            get {
                return ((float)(this["Palette_NTSC_hue_tweak"]));
            }
            set {
                this["Palette_NTSC_hue_tweak"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.5")]
        public float Palette_NTSC_saturation {
            get {
                return ((float)(this["Palette_NTSC_saturation"]));
            }
            set {
                this["Palette_NTSC_saturation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.07")]
        public float Palette_PALB_brightness {
            get {
                return ((float)(this["Palette_PALB_brightness"]));
            }
            set {
                this["Palette_PALB_brightness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.2")]
        public float Palette_PALB_contrast {
            get {
                return ((float)(this["Palette_PALB_contrast"]));
            }
            set {
                this["Palette_PALB_contrast"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.8")]
        public float Palette_PALB_gamma {
            get {
                return ((float)(this["Palette_PALB_gamma"]));
            }
            set {
                this["Palette_PALB_gamma"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float Palette_PALB_hue_tweak {
            get {
                return ((float)(this["Palette_PALB_hue_tweak"]));
            }
            set {
                this["Palette_PALB_hue_tweak"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.5")]
        public float Palette_PALB_saturation {
            get {
                return ((float)(this["Palette_PALB_saturation"]));
            }
            set {
                this["Palette_PALB_saturation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FrameSkip_Enabled {
            get {
                return ((bool)(this["FrameSkip_Enabled"]));
            }
            set {
                this["FrameSkip_Enabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public byte FrameSkip_Reload {
            get {
                return ((byte)(this["FrameSkip_Reload"]));
            }
            set {
                this["FrameSkip_Reload"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AUTO")]
        public global::MyNes.Core.TVSystemSetting TVSystemSetting {
            get {
                return ((global::MyNes.Core.TVSystemSetting)(this["TVSystemSetting"]));
            }
            set {
                this["TVSystemSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection RecentPlayed {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["RecentPlayed"]));
            }
            set {
                this["RecentPlayed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("English (United States)")]
        public string Language {
            get {
                return ((string)(this["Language"]));
            }
            set {
                this["Language"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int Audio_BufferSizeInMilliseconds {
            get {
                return ((int)(this["Audio_BufferSizeInMilliseconds"]));
            }
            set {
                this["Audio_BufferSizeInMilliseconds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Palette_UseGenerators {
            get {
                return ((bool)(this["Palette_UseGenerators"]));
            }
            set {
                this["Palette_UseGenerators"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Palette_FilePath {
            get {
                return ((string)(this["Palette_FilePath"]));
            }
            set {
                this["Palette_FilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AUTO")]
        public global::MyNes.PaletteGeneratorUsage Palette_GeneratorUsageMode {
            get {
                return ((global::MyNes.PaletteGeneratorUsage)(this["Palette_GeneratorUsageMode"]));
            }
            set {
                this["Palette_GeneratorUsageMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IgnoreNotSupportedMapper {
            get {
                return ((bool)(this["IgnoreNotSupportedMapper"]));
            }
            set {
                this["IgnoreNotSupportedMapper"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowRomIssuesIfHave {
            get {
                return ((bool)(this["ShowRomIssuesIfHave"]));
            }
            set {
                this["ShowRomIssuesIfHave"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AudioChannelSQ1Enabled {
            get {
                return ((bool)(this["AudioChannelSQ1Enabled"]));
            }
            set {
                this["AudioChannelSQ1Enabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AudioChannelSQ2Enabled {
            get {
                return ((bool)(this["AudioChannelSQ2Enabled"]));
            }
            set {
                this["AudioChannelSQ2Enabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AudioChannelDMCEnabled {
            get {
                return ((bool)(this["AudioChannelDMCEnabled"]));
            }
            set {
                this["AudioChannelDMCEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AudioChannelTRLEnabled {
            get {
                return ((bool)(this["AudioChannelTRLEnabled"]));
            }
            set {
                this["AudioChannelTRLEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AudioChannelNOZEnabled {
            get {
                return ((bool)(this["AudioChannelNOZEnabled"]));
            }
            set {
                this["AudioChannelNOZEnabled"] = value;
            }
        }
    }
}
