//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyNes.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("English (United States)")]
        public string Language {
            get {
                return ((string)(this["Language"]));
            }
            set {
                this["Language"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FileDB {
            get {
                return ((string)(this["FileDB"]));
            }
            set {
                this["FileDB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FolderSnapshots {
            get {
                return ((string)(this["FolderSnapshots"]));
            }
            set {
                this["FolderSnapshots"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FolderStates {
            get {
                return ((string)(this["FolderStates"]));
            }
            set {
                this["FolderStates"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FolderSrams {
            get {
                return ((string)(this["FolderSrams"]));
            }
            set {
                this["FolderSrams"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10, 10")]
        public global::System.Drawing.Point MainWindowLocation {
            get {
                return ((global::System.Drawing.Point)(this["MainWindowLocation"]));
            }
            set {
                this["MainWindowLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("528, 511")]
        public global::System.Drawing.Size MainWindowSize {
            get {
                return ((global::System.Drawing.Size)(this["MainWindowSize"]));
            }
            set {
                this["MainWindowSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection FileRecents {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["FileRecents"]));
            }
            set {
                this["FileRecents"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AudioSoundEnabled {
            get {
                return ((bool)(this["AudioSoundEnabled"]));
            }
            set {
                this["AudioSoundEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SaveSRAMOnShutdown {
            get {
                return ((bool)(this["SaveSRAMOnShutdown"]));
            }
            set {
                this["SaveSRAMOnShutdown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DirectX9")]
        public global::MyNes.VideoOutputMode VideoOutputMode {
            get {
                return ((global::MyNes.VideoOutputMode)(this["VideoOutputMode"]));
            }
            set {
                this["VideoOutputMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DirectSound")]
        public global::MyNes.SoundOutputMode AudioOutputMode {
            get {
                return ((global::MyNes.SoundOutputMode)(this["AudioOutputMode"]));
            }
            set {
                this["AudioOutputMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("44100")]
        public int AudioFrequency {
            get {
                return ((int)(this["AudioFrequency"]));
            }
            set {
                this["AudioFrequency"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::MyNes.ControlProfilesCollection InputProfiles {
            get {
                return ((global::MyNes.ControlProfilesCollection)(this["InputProfiles"]));
            }
            set {
                this["InputProfiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int InputProfileIndex {
            get {
                return ((int)(this["InputProfileIndex"]));
            }
            set {
                this["InputProfileIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float PaletteNTSCHue {
            get {
                return ((float)(this["PaletteNTSCHue"]));
            }
            set {
                this["PaletteNTSCHue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.2")]
        public float PaletteNTSCContrast {
            get {
                return ((float)(this["PaletteNTSCContrast"]));
            }
            set {
                this["PaletteNTSCContrast"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.8")]
        public float PaletteNTSCGamma {
            get {
                return ((float)(this["PaletteNTSCGamma"]));
            }
            set {
                this["PaletteNTSCGamma"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.07")]
        public float PaletteNTSCBrightness {
            get {
                return ((float)(this["PaletteNTSCBrightness"]));
            }
            set {
                this["PaletteNTSCBrightness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.5")]
        public float PaletteNTSCSaturation {
            get {
                return ((float)(this["PaletteNTSCSaturation"]));
            }
            set {
                this["PaletteNTSCSaturation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float PalettePALBHue {
            get {
                return ((float)(this["PalettePALBHue"]));
            }
            set {
                this["PalettePALBHue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.2")]
        public float PalettePALBContrast {
            get {
                return ((float)(this["PalettePALBContrast"]));
            }
            set {
                this["PalettePALBContrast"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.8")]
        public float PalettePALBGamma {
            get {
                return ((float)(this["PalettePALBGamma"]));
            }
            set {
                this["PalettePALBGamma"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.07")]
        public float PalettePALBBrightness {
            get {
                return ((float)(this["PalettePALBBrightness"]));
            }
            set {
                this["PalettePALBBrightness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.5")]
        public float PalettePALBSaturation {
            get {
                return ((float)(this["PalettePALBSaturation"]));
            }
            set {
                this["PalettePALBSaturation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float PaletteDENDYHue {
            get {
                return ((float)(this["PaletteDENDYHue"]));
            }
            set {
                this["PaletteDENDYHue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.2")]
        public float PaletteDENDYContrast {
            get {
                return ((float)(this["PaletteDENDYContrast"]));
            }
            set {
                this["PaletteDENDYContrast"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.8")]
        public float PaletteDENDYGamma {
            get {
                return ((float)(this["PaletteDENDYGamma"]));
            }
            set {
                this["PaletteDENDYGamma"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.07")]
        public float PaletteDENDYBrightness {
            get {
                return ((float)(this["PaletteDENDYBrightness"]));
            }
            set {
                this["PaletteDENDYBrightness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.5")]
        public float PaletteDENDYSaturation {
            get {
                return ((float)(this["PaletteDENDYSaturation"]));
            }
            set {
                this["PaletteDENDYSaturation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AUTO")]
        public global::MyNes.Core.TVSystemSettings TVFormat {
            get {
                return ((global::MyNes.Core.TVSystemSettings)(this["TVFormat"]));
            }
            set {
                this["TVFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".png")]
        public string SnapshotsFormat {
            get {
                return ((string)(this["SnapshotsFormat"]));
            }
            set {
                this["SnapshotsFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int AudioLatency {
            get {
                return ((int)(this["AudioLatency"]));
            }
            set {
                this["AudioLatency"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("85")]
        public int AudioVolume {
            get {
                return ((int)(this["AudioVolume"]));
            }
            set {
                this["AudioVolume"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16")]
        public short AudioBitsPerSample {
            get {
                return ((short)(this["AudioBitsPerSample"]));
            }
            set {
                this["AudioBitsPerSample"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public short AudioChannelsCount {
            get {
                return ((short)(this["AudioChannelsCount"]));
            }
            set {
                this["AudioChannelsCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool VideoLaunchFullscreen {
            get {
                return ((bool)(this["VideoLaunchFullscreen"]));
            }
            set {
                this["VideoLaunchFullscreen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool VideoCutLines {
            get {
                return ((bool)(this["VideoCutLines"]));
            }
            set {
                this["VideoCutLines"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool VideoImmediateMode {
            get {
                return ((bool)(this["VideoImmediateMode"]));
            }
            set {
                this["VideoImmediateMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool VideoKeepAspectRatio {
            get {
                return ((bool)(this["VideoKeepAspectRatio"]));
            }
            set {
                this["VideoKeepAspectRatio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool VideoShowFPS {
            get {
                return ((bool)(this["VideoShowFPS"]));
            }
            set {
                this["VideoShowFPS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool VideoShowNotifications {
            get {
                return ((bool)(this["VideoShowNotifications"]));
            }
            set {
                this["VideoShowNotifications"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int VideoFullscreenResIndex {
            get {
                return ((int)(this["VideoFullscreenResIndex"]));
            }
            set {
                this["VideoFullscreenResIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool VideoDirect9IsHardwareVertexProcessing {
            get {
                return ((bool)(this["VideoDirect9IsHardwareVertexProcessing"]));
            }
            set {
                this["VideoDirect9IsHardwareVertexProcessing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Point")]
        public global::SlimDX.Direct3D9.TextureFilter VideoDirect9Filter {
            get {
                return ((global::SlimDX.Direct3D9.TextureFilter)(this["VideoDirect9Filter"]));
            }
            set {
                this["VideoDirect9Filter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10, 10")]
        public global::System.Drawing.Point ConsoleWindowLocation {
            get {
                return ((global::System.Drawing.Point)(this["ConsoleWindowLocation"]));
            }
            set {
                this["ConsoleWindowLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("800, 600")]
        public global::System.Drawing.Size ConsoleWindowSize {
            get {
                return ((global::System.Drawing.Size)(this["ConsoleWindowSize"]));
            }
            set {
                this["ConsoleWindowSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FrameSkippingEnabled {
            get {
                return ((bool)(this["FrameSkippingEnabled"]));
            }
            set {
                this["FrameSkippingEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public byte FrameSkippingCount {
            get {
                return ((byte)(this["FrameSkippingCount"]));
            }
            set {
                this["FrameSkippingCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowMenu {
            get {
                return ((bool)(this["ShowMenu"]));
            }
            set {
                this["ShowMenu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowToolsBar {
            get {
                return ((bool)(this["ShowToolsBar"]));
            }
            set {
                this["ShowToolsBar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::MyNes.DBColumnCollection DBColumns {
            get {
                return ((global::MyNes.DBColumnCollection)(this["DBColumns"]));
            }
            set {
                this["DBColumns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10, 10")]
        public global::System.Drawing.Point BrowserWindowLocation {
            get {
                return ((global::System.Drawing.Point)(this["BrowserWindowLocation"]));
            }
            set {
                this["BrowserWindowLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("800, 600")]
        public global::System.Drawing.Size BrowserWindowSize {
            get {
                return ((global::System.Drawing.Size)(this["BrowserWindowSize"]));
            }
            set {
                this["BrowserWindowSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int BrowserThumbnailSize {
            get {
                return ((int)(this["BrowserThumbnailSize"]));
            }
            set {
                this["BrowserThumbnailSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int BrowserThumbnailModeIndex {
            get {
                return ((int)(this["BrowserThumbnailModeIndex"]));
            }
            set {
                this["BrowserThumbnailModeIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Details")]
        public global::MLV.ManagedListViewViewMode BrowserViewMode {
            get {
                return ((global::MLV.ManagedListViewViewMode)(this["BrowserViewMode"]));
            }
            set {
                this["BrowserViewMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool BrowserMinimizeWindowOnRomLoad {
            get {
                return ((bool)(this["BrowserMinimizeWindowOnRomLoad"]));
            }
            set {
                this["BrowserMinimizeWindowOnRomLoad"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MainWindowAutoPauseOnFocusLost {
            get {
                return ((bool)(this["MainWindowAutoPauseOnFocusLost"]));
            }
            set {
                this["MainWindowAutoPauseOnFocusLost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowStatus {
            get {
                return ((bool)(this["ShowStatus"]));
            }
            set {
                this["ShowStatus"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool HidingMenuForFirstTime {
            get {
                return ((bool)(this["HidingMenuForFirstTime"]));
            }
            set {
                this["HidingMenuForFirstTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int VideoWindowStretchMultiply {
            get {
                return ((int)(this["VideoWindowStretchMultiply"]));
            }
            set {
                this["VideoWindowStretchMultiply"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool VideoStretchWindowToFitSize {
            get {
                return ((bool)(this["VideoStretchWindowToFitSize"]));
            }
            set {
                this["VideoStretchWindowToFitSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoHideMouse {
            get {
                return ((bool)(this["AutoHideMouse"]));
            }
            set {
                this["AutoHideMouse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int AutoHideMousePeriod {
            get {
                return ((int)(this["AutoHideMousePeriod"]));
            }
            set {
                this["AutoHideMousePeriod"] = value;
            }
        }
    }
}
